version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=sistema_reservas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a.123456
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./WebApi/Dockerfile
    ports:
      - 80:8080
      - 81:8081
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
